require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('faker', '0.4.0') do |p|
  p.description    = "A port of Perl's Data::Faker library that generates fake data."
  p.url            = "http://github.com/neilmiddleton/Faker"
  p.author         = "Neil Middleton"
  p.email          = "neilmiddleton @nospam@ gmail.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end